### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by joesse** [edsu/feediverse#3]
When running feediverse the first time I get:
Traceback (most recent call last):
File "/usr/local/bin/feediverse", line 6, in <module>
    from feediverse import main
  File "/usr/local/lib/python2.7/dist-packages/feediverse.py", line 63
    return new_entries
SyntaxError: 'return' with argument inside generator

What can do to fix this?
Also: if I plan to run feediverse as a cron job, should I configure it as super user?

running on raspian 8.0 jessie

**Comment by htgoebel** [comment]
Which python version do you use?

**Comment by htgoebel** [comment]
> Also: if I plan to run feediverse as a cron job, should I configure it as super user?

Running any program as super user is bad idea in almost all cases. This is neither a system service nor does it require extra privileges. So: no, you should not run it as super user!

**Comment by joesse** [comment]
I am running Python 2.7.9

**Comment by htgoebel** [comment]
Python 2.7 does not allow `return` in generators. Please use pthon3 to run feediverse.

**Comment by edsu** [comment]
I've updated the setup.py to indicate python3 is required. Thanks for the bug report! 

PS. Don't run as root!!!
