### ISSUE TITLE
Reservse order of entries prior tp publishing

### ISSUE THREAD

**Issue by htgoebel** [edsu/feediverse#4]
Currently the entries of the feed are processed on the order they appear in the feed, which normally is newest to oldest. This will lead to the newer entries to be tooted first, which means that the older ones are above the newer ones in the mastodon timeline.

**Comment by steinarb** [comment]
In addition to fixing the order of posts, it would also be nice if the date of the toot could be set to the date of the RSS entry.

I used feediverse now to import summaries of all posts to my blog and they all appeared with the current date and, as this issue describes, in the wrong order.

**Comment by htgoebel** [comment]
@steinarb Looks like the APi does not support setting a creation time: https://docs.joinmastodon.org/methods/statuses/ only describes `created_at` as a return value from the server.
